# Generated by Django 5.1.3 on 2024-12-09 14:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0002_abstractclinicalemployee_employee_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractclinicalemployee',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='abstractclinicalemployee',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='clinicalemployee_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='clinicalemployee_permissions_set', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='username',
            field=models.CharField(default='Boris Isac', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
