# Generated by Django 5.1.3 on 2024-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_abstractclinicalemployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
