# Generated by Django 5.1.3 on 2024-12-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_abstractclinicalemployee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='is_staff',
            field=models.BooleanField(default=True, help_text=('Designates whether the user can log into this admin site.',), verbose_name=('staff status',)),
        ),
    ]
