# Generated by Django 5.1.3 on 2024-12-09 14:55

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_abstractclinicalemployee_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRClinicalEmployee',
            fields=[
                ('abstractclinicalemployee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.abstractclinicalemployee')),
                ('medical_order_ID', models.CharField(help_text="A unique identifier for the medical order assigned to this user. This ID is used to track the user's medical orders.", unique=True, verbose_name='Medical Order ID')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('employees.abstractclinicalemployee',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
