# Generated by Django 5.1.3 on 2024-12-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_drclinicalemployee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractclinicalemployee',
            options={'verbose_name': 'Clinical Employee', 'verbose_name_plural': 'Clinical Employees'},
        ),
        migrations.AlterModelOptions(
            name='drclinicalemployee',
            options={'verbose_name': 'DR', 'verbose_name_plural': "DR's"},
        ),
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='contact_number',
            field=models.CharField(default='919293949596'),
            preserve_default=False,
        ),
    ]
