# Generated by Django 5.1.3 on 2024-12-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_abstractclinicalemployee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractclinicalemployee',
            name='employee_type',
        ),
    ]
