# Generated by Django 5.1.3 on 2024-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_abstractclinicalemployee_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='employee_type',
            field=models.CharField(choices=[('DR', 'DR'), ('RECEPTION', 'RECEPTION')], default='DR'),
        ),
    ]
