# Generated by Django 5.1.3 on 2024-12-10 11:48

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_abstractclinicalemployee_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionsClinicalEmployee',
            fields=[
                ('abstractclinicalemployee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.abstractclinicalemployee')),
            ],
            options={
                'verbose_name': 'Reception',
                'verbose_name_plural': 'Receptions',
            },
            bases=('employees.abstractclinicalemployee',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
