# Generated by Django 5.1.3 on 2024-12-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_receptionsclinicalemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptionsclinicalemployee',
            options={'verbose_name': 'Reception Assistant', 'verbose_name_plural': "Reception's Assistant"},
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='username',
            field=models.CharField(),
        ),
    ]
