# Generated by Django 5.1.3 on 2024-12-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_receptionsclinicalemployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
