# Generated by Django 5.1.3 on 2025-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_abstractclinicalemployee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractclinicalemployee',
            name='gender_employee',
            field=models.CharField(choices=[('Click to select', 'Click to select'), ('Male', 'Male'), ('Female', 'Female')], default='Click to select', max_length=50),
        ),
        migrations.AddField(
            model_name='drclinicalemployee',
            name='speciality_type',
            field=models.CharField(choices=[('Click to select', 'Click to select'), ('SPECIALITY1', 'SPECIALITY1'), ('SPECIALITY2', 'SPECIALITY2'), ('SPECIALITY3', 'SPECIALITY3'), ('SPECIALITY4', 'SPECIALITY4'), ('SPECIALITY5', 'SPECIALITY5'), ('SPECIALITY6', 'SPECIALITY6')], default='Click to select'),
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='employee_type',
            field=models.CharField(choices=[('Click to select', 'Click to select'), ('DR', 'DR'), ('RECEPTION', 'RECEPTION')], default='Click to select', max_length=50),
        ),
    ]
