# Generated by Django 5.1.3 on 2025-01-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_abstractclinicalemployee_gender_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drclinicalemployee',
            name='speciality_type',
            field=models.CharField(choices=[('Click to select', 'Click to select'), ('SPECIALITY1', 'SPECIALITY1'), ('SPECIALITY2', 'SPECIALITY2'), ('SPECIALITY3', 'SPECIALITY3'), ('SPECIALITY4', 'SPECIALITY4'), ('SPECIALITY5', 'SPECIALITY5'), ('SPECIALITY6', 'SPECIALITY6')], default='Click to select', max_length=50),
        ),
    ]
