# Generated by Django 5.1.3 on 2024-12-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='slug',
            field=models.SlugField(max_length=256),
        ),
    ]
