# Generated by Django 5.1.3 on 2024-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_date', models.DateField()),
                ('scheduling_time', models.TimeField()),
                ('medication_consultation', models.CharField(choices=[('MICRONUTRIENTS', 'Micronutrients'), ('GENERAL_MEDICINE', 'General Medicine'), ('DERMOCOSMETICS', 'Dermocosmetics'), ('ESTETICS_AND_COSMETICS', 'Estetics and Cosmetics'), ('ANTI_AGING_CONSULTATION', 'Anti-aging Medical Consultation'), ('FOLLOW_UP', 'Follow-up'), ('DERMOCOSMETICS_ONLINE', 'Dermocosmetics Online'), ('ESTETICS_AND_COSMETICS_ONLINE', 'Estetics and Cosmetics Online'), ('FOLLOW_UP_ANTI_AGING', 'Follow-up Anti-aging'), ('FREE_CLINICAL_ASSISTANCE', 'Free Clinical Assistance'), ('MAGRESS_ONLINE', 'Magress Online'), ('HAIR_MEDICINE_AND_TRICHOLOGY', 'Hair Medicine and Trichology'), ('COSMETIC_MICROSURGERY', 'Consultation for Cosmetic Microsurgery')], default='Change a consultation')),
                ('price', models.FloatField()),
                ('scheduling_id', models.SlugField()),
            ],
        ),
    ]
