# Generated by Django 5.1.3 on 2024-12-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_abstractclinicalemployee_employee_type'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='dr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='employees.drclinicalemployee'),
            preserve_default=False,
        ),
    ]
