# Generated by Django 5.1.3 on 2024-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_customer_id_services_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='medication_consultation',
            field=models.CharField(choices=[('MICRONUTRIENTS', 'Micronutrients'), ('GENERAL_MEDICINE', 'General Medicine'), ('DERMOCOSMETICS', 'Dermocosmetics'), ('ESTETICS_AND_COSMETICS', 'Estetics and Cosmetics'), ('ANTI_AGING_CONSULTATION', 'Anti-aging Medical Consultation'), ('FOLLOW_UP', 'Follow-up'), ('DERMOCOSMETICS_ONLINE', 'Dermocosmetics Online'), ('ESTETICS_AND_COSMETICS_ONLINE', 'Estetics and Cosmetics Online'), ('FOLLOW_UP_ANTI_AGING', 'Follow-up Anti-aging'), ('FREE_CLINICAL_ASSISTANCE', 'Free Clinical Assistance'), ('MAGRESS_ONLINE', 'Magress Online'), ('HAIR_MEDICINE_AND_TRICHOLOGY', 'Hair Medicine and Trichology'), ('COSMETIC_MICROSURGERY', 'Consultation for Cosmetic Microsurgery')], default='MICRONUTRIENTS'),
        ),
        migrations.AlterField(
            model_name='services',
            name='scheduling_id',
            field=models.CharField(max_length=10),
        ),
    ]
