# Generated by Django 5.1.3 on 2024-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
