# Generated by Django 5.1.3 on 2024-12-10 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='reserved_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 11, 48, 28, 937442)),
        ),
        migrations.AddField(
            model_name='services',
            name='reserved_by',
            field=models.CharField(blank=True),
        ),
    ]
