# Generated by Django 5.1.3 on 2024-12-10 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_reserved_at_services_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='reserved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
