# Generated by Django 5.1.3 on 2024-12-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_abstractclinicalemployee_username'),
        ('services', '0007_alter_services_reserved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='reserved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='employees.receptionsclinicalemployee'),
        ),
    ]
