# Generated by Django 5.1.3 on 2024-12-10 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_services_reserved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='scheduling_time',
            new_name='scheduling_time_finish',
        ),
        migrations.AddField(
            model_name='services',
            name='scheduling_time_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
