# Generated by Django 5.1.3 on 2024-12-10 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_scheduling_time_services_scheduling_time_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='old_procedures',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
