# Generated by Django 5.1.3 on 2024-12-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_services_old_procedures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='reserved_at',
            new_name='reserved_on',
        ),
    ]
