# Generated by Django 5.1.3 on 2024-12-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customers_email'),
        ('employees', '0012_alter_abstractclinicalemployee_username'),
        ('services', '0011_rename_reserved_at_services_reserved_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.customers'),
        ),
        migrations.AlterField(
            model_name='services',
            name='dr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.drclinicalemployee'),
        ),
        migrations.AlterField(
            model_name='services',
            name='reserved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.receptionsclinicalemployee'),
        ),
    ]
